import tailwindcss from '@tailwindcss/vite'

const title = 'EnBizCard - An Open-Source Digital Business Card Generator'
const description =
  'EnBizCard helps you create beautiful, responsive HTML-based digital business cards that can be hosted on your website.'
const themeColor = '#111827'

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',

  // Prerender to real HTML where we can. There is still no backend — SSR here
  // only means `nuxt generate` emits populated markup instead of empty shells.
  ssr: true,

  routeRules: {
    // The generator itself must stay client-only: Preview.vue renders a whole
    // nested <html>/<head>/<body> document, and the browser's HTML parser
    // discards tags like those inside a <div>, so server markup could never
    // match the client render. This route is emitted as an SPA shell.
    '/': { ssr: false },
  },

  nitro: {
    prerender: {
      // '/' is an SPA shell, so the link crawler has no markup to walk and
      // cannot discover the other routes on its own. List them explicitly.
      routes: ['/hosting-guide'],
      crawlLinks: true,
    },
  },

  devtools: { enabled: false },
  telemetry: false,

  modules: ['@vite-pwa/nuxt'],

  // Tailwind 4 ships as a Vite plugin; there is no Nuxt module and no
  // tailwind.config.js — see app/assets/css/tailwind.css for the config.
  css: ['~/assets/css/tailwind.css'],
  vite: {
    plugins: [tailwindcss()],
  },

  app: {
    // Vue 2's `transition: 'page'` page option is replaced by app-level config.
    pageTransition: { name: 'page', mode: 'out-in' },
    head: {
      title,
      htmlAttrs: { lang: 'en' },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: description },
        { name: 'author', content: 'Vishnu Raghav' },
        { name: 'theme-color', content: themeColor },
        { name: 'msapplication-TileColor', content: themeColor },
        { name: 'msapplication-TileImage', content: '/mstile-150x150.png' },
        // Open Graph — previously generated by @nuxtjs/pwa's meta module.
        { property: 'og:type', content: 'website' },
        { property: 'og:title', content: title },
        { property: 'og:description', content: description },
        { property: 'og:site_name', content: title },
        { property: 'og:image', content: '/maskable_512.png' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico?v=2' },
        { rel: 'icon', type: 'image/png', href: '/favicon-16x16.png' },
        { rel: 'icon', type: 'image/png', href: '/favicon-32x32.png' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
        { rel: 'mask-icon', color: themeColor, href: '/safari-pinned-tab.svg' },
      ],
      // QR code generator is a plain global script served from public/.
      script: [{ src: '/qrcode.min.js' }],
    },
  },

  pwa: {
    registerType: 'autoUpdate',
    manifest: {
      name: title,
      short_name: 'EnBizCard',
      description,
      start_url: '/',
      display: 'standalone',
      theme_color: themeColor,
      background_color: themeColor,
      icons: [64, 120, 144, 152, 192, 384, 512].flatMap((size) => [
        {
          src: `/icon_${size}.png`,
          sizes: `${size}x${size}`,
          type: 'image/png',
        },
        {
          src: `/maskable_${size}.png`,
          sizes: `${size}x${size}`,
          type: 'image/png',
          purpose: 'maskable' as const,
        },
      ]),
    },
    workbox: {
      // The generated card bundles can be large; don't try to precache them.
      globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
    },
    devOptions: { enabled: false },
  },
})
